### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by clementdessoude** [camunda/camunda-bpm-junit5#1]
Hi !

It would be wonderful to be able to run unit test with Camunda on JUnit 5 ! Would it be possible to contribute to this plugin ? Is there a roadmap or a plan to migrate from JUnit4 to Junit5 ?

**Comment by ingorichtsmeier** [comment]
Hi @clementdessoude,

as this is open source under Apache 2.0 license, you can contribute and I like to discuss your proposals. Just create one or more pull requests to this repo.

The plan is to publish this repo as soon as possible to maven central and make it available for every developer and encourage them to write JUnit test with the latest available JUnit version.

There is no plan to migrate from JUnit4 to Junit5 as both versions can be used in a project.

Hope this helps, Ingo

**Comment by itsmestefanjay** [comment]
Hi Ingo,

Any info when it will be available in the central repos? We'd like to use it in our project but the dependency has not yet popped up anywhere.

Thanks
Stefan

**Comment by ingorichtsmeier** [comment]
Hi @itsmestefanjay,

the initial version1.0.0 is now available on maven central.

I'm happy about any feedback.

Cheers, Ingo

**Comment by clementdessoude** [comment]
Hi @ingorichtsmeier ! 

Thank you for the release! I tried yesterday evening and it seems working fine, great job!

I'll provide more feedback if I see anything wrong or strange ;)

Thank you once again!
